spring:
    application:
        name: my-application

    datasource:
        url: jdbc:postgresql://localhost:5432/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp.auth: true
                smtp.starttls.enable: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwt-key: ${JWT_KEY}

    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
